### ISSUE TITLE
License

### ISSUE THREAD

**Issue by zbraniecki** [jfkthame/mapped_hyph#6]
Intl related crates that we use for Gecko but also offer to the wider Rust audience are all dual-licensed as MIT/Apache:

 - ruct_unic - https://github.com/open-i18n/rust-unic
 - intl_pluralrules - https://github.com/zbraniecki/pluralrules/tree/master/intl_pluralrules
 - unicode-rs - https://github.com/unicode-rs
 - unic-locale - https://github.com/zbraniecki/unic-locale

Is there a chance this could also get MIT/Apache license coverage? This would help us unify around MIT/Apache as we try to rewrite ICU.

**Comment by jfkthame** [comment]
OK, it sounds like we should switch this to MIT/Apache2.0 (and drop MPL, to keep things a bit simpler).

@djg, given that you've had a couple of PRs merged here, we'd better check with you: any objection to such a change?

**Comment by djg** [comment]
I have no problem with switching the licensing.

**Comment by jfkthame** [comment]
Cool, thanks -- I'll push a change to do this before (re-)vendoring the code into Gecko.
